/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as StudyPlanRouteImport } from './routes/study-plan'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CgpaRouteImport } from './routes/cgpa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadPdfIdRouteImport } from './routes/read.$pdfId'
import { Route as LibraryItemIdRouteImport } from './routes/library.$itemId'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice/speak'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlanRoute = StudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CgpaRoute = CgpaRouteImport.update({
  id: '/cgpa',
  path: '/cgpa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadPdfIdRoute = ReadPdfIdRouteImport.update({
  id: '/read/$pdfId',
  path: '/read/$pdfId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryItemIdRoute = LibraryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => LibraryRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgpa': typeof CgpaRoute
  '/chat': typeof ChatRoute
  '/exam': typeof ExamRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRouteWithChildren
  '/predictor': typeof PredictorRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-plan': typeof StudyPlanRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/library/$itemId': typeof LibraryItemIdRoute
  '/read/$pdfId': typeof ReadPdfIdRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgpa': typeof CgpaRoute
  '/chat': typeof ChatRoute
  '/exam': typeof ExamRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRouteWithChildren
  '/predictor': typeof PredictorRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-plan': typeof StudyPlanRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/library/$itemId': typeof LibraryItemIdRoute
  '/read/$pdfId': typeof ReadPdfIdRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgpa': typeof CgpaRoute
  '/chat': typeof ChatRoute
  '/exam': typeof ExamRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRouteWithChildren
  '/predictor': typeof PredictorRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-plan': typeof StudyPlanRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/library/$itemId': typeof LibraryItemIdRoute
  '/read/$pdfId': typeof ReadPdfIdRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cgpa'
    | '/chat'
    | '/exam'
    | '/how-it-works'
    | '/library'
    | '/predictor'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/study-plan'
    | '/upgrade'
    | '/admin/payments'
    | '/library/$itemId'
    | '/read/$pdfId'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cgpa'
    | '/chat'
    | '/exam'
    | '/how-it-works'
    | '/library'
    | '/predictor'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/study-plan'
    | '/upgrade'
    | '/admin/payments'
    | '/library/$itemId'
    | '/read/$pdfId'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cgpa'
    | '/chat'
    | '/exam'
    | '/how-it-works'
    | '/library'
    | '/predictor'
    | '/profile'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/study-plan'
    | '/upgrade'
    | '/admin/payments'
    | '/library/$itemId'
    | '/read/$pdfId'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CgpaRoute: typeof CgpaRoute
  ChatRoute: typeof ChatRoute
  ExamRoute: typeof ExamRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  PredictorRoute: typeof PredictorRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyPlanRoute: typeof StudyPlanRoute
  UpgradeRoute: typeof UpgradeRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  ReadPdfIdRoute: typeof ReadPdfIdRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-plan': {
      id: '/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof StudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgpa': {
      id: '/cgpa'
      path: '/cgpa'
      fullPath: '/cgpa'
      preLoaderRoute: typeof CgpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$pdfId': {
      id: '/read/$pdfId'
      path: '/read/$pdfId'
      fullPath: '/read/$pdfId'
      preLoaderRoute: typeof ReadPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$itemId': {
      id: '/library/$itemId'
      path: '/$itemId'
      fullPath: '/library/$itemId'
      preLoaderRoute: typeof LibraryItemIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibraryItemIdRoute: typeof LibraryItemIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryItemIdRoute: LibraryItemIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CgpaRoute: CgpaRoute,
  ChatRoute: ChatRoute,
  ExamRoute: ExamRoute,
  HowItWorksRoute: HowItWorksRoute,
  LibraryRoute: LibraryRouteWithChildren,
  PredictorRoute: PredictorRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyPlanRoute: StudyPlanRoute,
  UpgradeRoute: UpgradeRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  ReadPdfIdRoute: ReadPdfIdRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
