/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyPlanRouteImport } from './routes/study-plan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CgpaRouteImport } from './routes/cgpa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadPdfIdRouteImport } from './routes/read.$pdfId'

const StudyPlanRoute = StudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CgpaRoute = CgpaRouteImport.update({
  id: '/cgpa',
  path: '/cgpa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadPdfIdRoute = ReadPdfIdRouteImport.update({
  id: '/read/$pdfId',
  path: '/read/$pdfId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgpa': typeof CgpaRoute
  '/chat': typeof ChatRoute
  '/how-it-works': typeof HowItWorksRoute
  '/predictor': typeof PredictorRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/study-plan': typeof StudyPlanRoute
  '/read/$pdfId': typeof ReadPdfIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgpa': typeof CgpaRoute
  '/chat': typeof ChatRoute
  '/how-it-works': typeof HowItWorksRoute
  '/predictor': typeof PredictorRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/study-plan': typeof StudyPlanRoute
  '/read/$pdfId': typeof ReadPdfIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgpa': typeof CgpaRoute
  '/chat': typeof ChatRoute
  '/how-it-works': typeof HowItWorksRoute
  '/predictor': typeof PredictorRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/study-plan': typeof StudyPlanRoute
  '/read/$pdfId': typeof ReadPdfIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cgpa'
    | '/chat'
    | '/how-it-works'
    | '/predictor'
    | '/profile'
    | '/search'
    | '/settings'
    | '/study-plan'
    | '/read/$pdfId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cgpa'
    | '/chat'
    | '/how-it-works'
    | '/predictor'
    | '/profile'
    | '/search'
    | '/settings'
    | '/study-plan'
    | '/read/$pdfId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cgpa'
    | '/chat'
    | '/how-it-works'
    | '/predictor'
    | '/profile'
    | '/search'
    | '/settings'
    | '/study-plan'
    | '/read/$pdfId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CgpaRoute: typeof CgpaRoute
  ChatRoute: typeof ChatRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PredictorRoute: typeof PredictorRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StudyPlanRoute: typeof StudyPlanRoute
  ReadPdfIdRoute: typeof ReadPdfIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-plan': {
      id: '/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof StudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgpa': {
      id: '/cgpa'
      path: '/cgpa'
      fullPath: '/cgpa'
      preLoaderRoute: typeof CgpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$pdfId': {
      id: '/read/$pdfId'
      path: '/read/$pdfId'
      fullPath: '/read/$pdfId'
      preLoaderRoute: typeof ReadPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CgpaRoute: CgpaRoute,
  ChatRoute: ChatRoute,
  HowItWorksRoute: HowItWorksRoute,
  PredictorRoute: PredictorRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StudyPlanRoute: StudyPlanRoute,
  ReadPdfIdRoute: ReadPdfIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
